baseurl = "https://www.tristandefommervault.com/"
footnoteReturnLinkContents = "↩"
languageCode = "fr-fr"
metaDataFormat = "yaml"
removePathAccents = true
theme = "elate"
title = "Tristan de Fommervault coach"
[[menu.postpend]]
name = "Bio"
url = "/bio"
weight = 3
[[menu.postpend]]
name = "Formations"
url = "/formations"
weight = 2
[[menu.postpend]]
name = "Articles"
url = "/articles"
weight = 1
[params]
author = "Tristan de Fommervault"
custom_css = ["css/custom1.css"]
description = "Coaching professionnel,mentoring,codéveloppement,process communication, approche systémique, analyse transactionnelle, communication non violente, intelligence émotionnelle, psychologie de la motivation, gestion du stress,prise de décision,régulation des conflits, médiation en entreprise, prévention des risques psychosociaux, "
email = "tdefommervault@qualia-management.com"
[params.about]
description = "Profils des intervenants"
enable = false
title = "Qui sommes-nous ?"
[[params.about.item]]
alt = "Tristan de Fommervault"
description = "."
img = "tristan.jpg"
name = "Tristan de Fommervault"
position = "Coach et formateur certifié (Process Com., Desu Paris 8 et Trajectives). Sciences Po, M2 Philosophie Sorbonne, Conservatoire de théâtre Paris. Tristan a développé durant 15 ans une approche humaniste* de l'accompagnement des personnes et des collectifs en situation de transformation. Qualité d'écoute et de présence, enthousiasme communicatif, théâtralise avec justesse pour rendre acteur.  *éthique et nourrie de nos humanités"
social = [["icon-twitter", "https://twitter.com/de_Fommervault"], ["icon-facebook", "https://www.facebook.com/fommervault?ref=bookmarks"], ["icon-linkedin", "https://www.linkedin.com/in/tristandefommervault/"]]
[[params.about.item]]
alt = "lena"
description = "Fondatrice du cabinet de coaching Acara. Auparavant Responsable des programmes internationaux de formation à l'ENA."
img = "lena.jpg"
name = "Léna Badach"
position = "Partenaire experte en pédagogie, coach et formatrice certifiée Process Com."
social = [["icon-linkedin", "https://www.linkedin.com/in/tristandefommervault/"]]
[params.articles]
description = "Food for thought"
enable = true
title = "Articles"
[params.contact]
button = "Envoyer"
description = ""
details = [["icon-home", "36 rue de Fleurus, <br> 75006 Paris"], ["icon-phone", "+33(0)6 61 07 90 51"], ["icon-envelope", "tdefommervault@qualia-management.com"], ["icon-globe", "<a href=\"https://tristandefommervault.com/\" target=\"_blank\">tristandefommervault.com</a>"]]
email = "Email"
enable = true
form = true
map = false
message = "Message"
name = "Nom"
phone = "Téléphone"
title = "Contact"
[params.counters]
background = "full_image_1.jpg"
enable = false
title = "Stats"
[[params.counters.item]]
description = "Finished projects"
from = 0
icon = "icon-briefcase"
interval = 50
speed = 5000
to = 89
[[params.counters.item]]
description = "Formations"
from = 0
icon = "icon-code"
interval = 50
speed = 5000
to = 2000
[[params.counters.item]]
description = "Cups of coffee"
from = 0
icon = "icon-cup"
interval = 50
speed = 5000
to = 1302
[[params.counters.item]]
description = "Happy clients"
from = 0
icon = "icon-people"
interval = 50
speed = 5000
to = 52
[params.footer]
copyright = "&copy; Tristan de Fommervault. Tous droits réservés."
enable = true
links = [["icon-facebook", "https://www.facebook.com/tristandefommervault"], ["icon-linkedin", "https://fr.linkedin.com/in/tristandefommervault/fr"]]
[params.hero]
subtitle = "Se recentrer sur ses essentiels pour s'accomplir pleinement"
title = "COACHING"
[params.hero0]
subtitle = "Le coaching tel que je le pratique consiste en un itinéraire dialogué à la fois ouvert et guidé qui permet à la personne d’aller puiser dans ses situations vécues pour remonter graduellement à la source de ses intentions directrices, de son désir profond et de son énergie d’action. Ainsi recentrée, la personne développe durant l'accompagnement sa conscience de ses modes d'interaction et aiguise sa capacité à agir sur la base de stratégies efficaces dans le respect de son identité."
title = "Mon approche"
[params.intro.video]
enable = false
icon = "icon-play2"
title = "Voir la vidéo"
url = "https://vimeo.com/channels/staffpicks/93951774"
[[params.intro.item]]
button = ""
description = ""
icon = ""
img = ""
title = "Vous avez besoin de lever une difficulté ou un blocage qui stoppe votre avancée dans un projet"
url = ""
[[params.intro.item]]
description = ""
icon = ""
img = ""
title = " Vous désirez initier un changement dans votre vie professionnelle mais vous vous posez des questions"
[[params.intro.item]]
description = ""
icon = ""
img = ""
title = " Vous avez 100 jours pour réussir votre prise de poste et avez besoin de vous recentrer sur vos priorités"
[[params.intro.item]]
description = ""
icon = ""
img = ""
title = " Vous avez besoin de faire le point sur vos véritables forces et qualités pour retrouver confiance en vous et pouvoir jouer pleinement votre rôle"
[[params.intro.item]]
description = ""
icon = ""
img = ""
title = " Vous ressentez le besoin de reprendre en main votre GPS émotionnel "
[[params.intro.item]]
description = ""
icon = ""
img = ""
title = "Vous prenez conscience des limites de vos comportements sous stress et souhaitez développer une posture relationnelle constructive"
[[params.intro.item]]
description = ""
icon = ""
img = ""
title = "La question du sens de votre travail vous 'travaille' et vous avez besoin d'un espace pour consacrer à cette question essentielle le temps nécessaire"
[[params.intro.item]]
description = ""
icon = ""
img = ""
title = "Vous avez besoin de résoudre un conflit avec l'impression d'avoir déjà tout essayé"
[[params.intro.item]]
description = ""
icon = ""
img = ""
title = "Vous avez besoin de vous recentrer sur vos véritables qualités distinctives qui font votre réelle différence"
[params.navigation]
about = "À propos"
brand = "Tristan de Fommervault"
contact = "Contact"
home = "Accueil"
services = "Services"
testimonials = "Témoignages"
work = "Références"
[params.services]
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
enable = false
title = "Services"
[[params.services.item]]
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
icon = "icon-anchor"
title = "Brand &amp; Strategy"
[[params.services.item]]
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
icon = "icon-layers2"
title = "Web &amp; Interface"
[[params.services.item]]
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
icon = "icon-video2"
title = "Photo &amp; Video"
[[params.services.item]]
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
icon = "icon-monitor"
title = "CMS &amp; eCommerce"
[params.testimonials]
description = ""
enable = true
title = "Témoignages"
[[params.testimonials.item]]
alt = "Sébastien Rémond"
img = "person1.jpg"
person = "Sébastien Remond, <a href=\"https://cib.societegenerale.com/en/\" target=\"_blank\">Société Générale CIB</a> <span class=\"subtext\">Directeur Investment Banking</span>"
quote = "&ldquo;Tristan a beaucoup apporté à ces ateliers grâce à sa personnalité engageante, son esprit d’ouverture et sa capacité à connecter des problématiques professionnelles avec une approche différente.&rdquo;"
[[params.testimonials.item]]
alt = "Catherine Belotti"
img = "person2.jpg"
person = "Catherine Belotti, <span class=\"subtext\">Directrice innovation sociale Schneider Electric</span>"
quote = "&ldquo;Tristan a fait preuve d'une grande intelligence des situations dans un contexte de transformation majeure de l'entreprise.&rdquo;"
[[params.testimonials.item]]
alt = "Grégoire hallé"
img = "person3.jpg"
person = "Grégoire Hallé, Conservateur du Patrimoine, Musée des Beaux-Arts de Draguignan"
quote = "&ldquo;J’avais besoin de reprendre confiance en moi dans le cadre d’une négociation. Ses grandes qualités d’écoute et d’analyse m'ont aidé à mettre au point, au fil des séances de coaching, une stratégie pour gérer ma situation de manière optimale.&rdquo;"
[[params.testimonials.item]]
alt = "Stéphanie Baranger"
img = "person4.jpg"
person = "Stéphanie Baranger, Chief of staff to the Global Head of HR - Global Banking and Investor Solutions - Société Générale"
quote = "&ldquo;J’ai eu le plaisir de travailler avec Tristan sur un parcours de développement managérial (...) En faisant émerger une communauté de pratiques managériales consciente da sa valeur ajoutée, l’accompagnement de Tristan nous a permis d’aller bien au delà de l’objectif initial.&rdquo;"
[[params.testimonials.item]]
alt = "Verbatim1"
img = "person2.jpg"
person = "Verbatim évaluation à chaud"
quote = "&ldquo;Par la justesse de ses reformulations et feedbacks, Tristan a réussi à susciter chez les participants un changement de regard et l’envie d’oser. Tristan est un formateur qui sait créer un climat d'écoute, de bienveillance mais aussi de confrontation constructive.&rdquo;"
[[params.testimonials.item]]
alt = "Verbatim2"
img = "person1.jpg"
person = "Verbatim évaluation à chaud"
quote = "&ldquo;Tristan mobilise l'energie du groupe en jouant sur une grande variété de ressorts.&rdquo;"
[params.work]
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
enable = false
footertext = "** Demo images from <a href=\"http://plmd.me/\" target=\"_blank\">plmd.me</a>"
title = "Work"
[[params.work.row]]
alt = "Image2"
img = "work_1.jpg"
subtitle = "Branding"
title = "Project 1"
[[params.work.row]]
alt = "Image2"
img = "work_2.jpg"
subtitle = "Design"
title = "Project 2"
[[params.work.row]]
alt = "Image3"
img = "work_3.jpg"
subtitle = "Design"
title = "Project 3"
[[params.work.row]]
alt = "Image4"
img = "work_4.jpg"
subtitle = "Design"
title = "Project 4"
[[params.work.row]]
alt = "Image5"
img = "work_5.jpg"
subtitle = "Design"
title = "Project 5"
[[params.work.row]]
alt = "Image6"
img = "work_6.jpg"
subtitle = "Design"
title = "Project 6"
