baseurl = "https://www.tristandefommervault.com/"
footnoteReturnLinkContents = "↩"
brand : Qualia
languageCode = "fr-fr"
metaDataFormat = "yaml"
pluralizeListTitles = false
removePathAccents = true
theme = "github.com/saey55/hugo-elate-theme"
title = "Tristan de Fommervault - Coach"
[[menu.postpend]]
name = "Séance gratuite"
url = "https://calendly.com/tristandefommervault/seance-exploratoire"
weight = 3
[[menu.postpend]]
name = "Formations"
url = "/formations"
weight = 1
[[menu.postpend]]
name = "Articles"
url = "/articles"
weight = 2
[params]
author = "Tristan de Fommervault"
custom_css = ["css/custom1.css"]
description = "Coach professionnel certifié, j'accompagne les personnes en transition pour accélérer l'atteinte de leur objectif et transformer leur ambition en joie de la réaliser. Me contacter : 0661079051. Possibilité de séances en visio"
email = "tdefommervault@qualia-management.com"
[params.about]
description = ""
enable = true
title = "À propos"
[[params.about.item]]
alt = "Tristan de Fommervault"
description = "Un parcours en 3 temps : Comédien, RH, Coach Formateur. J'accompagne les personnes et les collectifs en situation de transformation. Une citation qui m'inspire : Veille à tes pensées, elles deviennent des mots. Veille à tes mots, ils deviennent des actions. Veille à tes actions, elles deviennent des habitudes. Veille à tes habitudes, elles deviennent ton caractère. Veille à ton caractère, il devient ton destin. Lao Tseu "
img = "tristan2.jpg"
name = "Tristan de Fommervault"
position = "Coach et formateur certifié"
social = [["icon-twitter", "https://twitter.com/de_Fommervault"], ["icon-facebook", "https://www.facebook.com/fommervault?ref=bookmarks"], ["icon-linkedin", "https://www.linkedin.com/in/tristandefommervault/"]]
[params.articles]
description = "Derniers écrits"
enable = true
title = "Articles"
[params.contact]
button = "Envoyer"
description = ""
details = [["icon-home", "36 rue de Fleurus, <br> 75006 Paris"], ["icon-phone", "+33(0)6 61 07 90 51"], ["icon-envelope", "tdefommervault@qualia-management.com"], ["icon-globe", "<a href=\"https://tristandefommervault.com/\" target=\"_blank\">tristandefommervault.com</a>"]]
email = "Email"
enable = true
form = true
map = false
message = "Message"
name = "Nom"
phone = "Téléphone"
title = "Contact"
[params.counters]
enable = false
[params.footer]
copyright = "Tristan de Fommervault, [Formateur](/formations) & Coach."
enable = true
links = [["icon-facebook", "https://www.facebook.com/tristandefommervault"], ["icon-linkedin", "https://fr.linkedin.com/in/tristandefommervault/fr"]]
[params.hero]
subtitle = "Des formules d’accompagnement sur mesure pour vous aider à atteindre vos objectifs."
title = "Transmettre et accompagner, former et coacher"
[params.intro]
enable = true
[params.intro.video]
enable = true
[[params.intro.item]]
button = "En savoir plus"
description = "Un accompagnement personnalisé pour accélérer l'atteinte de son objectif et accomplir son rêve."
icon = "icon-target"
img = "img_7.jpg"
title = "Coaching"
url = "/coaching"
[[params.intro.item]]
button = "Voir le catalogue"
description = "Des formations sur mesure, ludiques, concrètes et digitalisées pour développer vos compétences de leadership"
icon = "icon-bulb"
img = "img_7.jpg"
title = "Formation"
url = "/formations"
[params.navigation]
about = "Coach"
brand = "Tristan de Fommervault"
contact = "Contact"
home = "Accueil"
intro = "Services"
testimonials = "Témoignages"
[params.services]
enable = false
[params.testimonials]
description = ""
enable = true
title = "Témoignages"
[[params.testimonials.item]]
alt = "Sébastien Rémond"
img = "person1.jpg"
person = "Sébastien Remond, <a href=\"https://cib.societegenerale.com/en/\" target=\"_blank\">Société Générale CIB</a> <span class=\"subtext\">Directeur Investment Banking</span>"
quote = "&ldquo;Tristan a beaucoup apporté à ces ateliers grâce à sa personnalité engageante, son esprit d’ouverture et sa capacité à connecter des problématiques professionnelles avec une approche différente.&rdquo;"
[[params.testimonials.item]]
alt = "Catherine Belotti"
img = "person2.jpg"
person = "Catherine Belotti, <span class=\"subtext\">Directrice innovation sociale Schneider Electric</span>"
quote = "&ldquo;Tristan a fait preuve d'une grande intelligence des situations dans un contexte de transformation majeure de l'entreprise.&rdquo;"
[[params.testimonials.item]]
alt = "Grégoire hallé"
img = "person3.jpg"
person = "Grégoire Hallé, Conservateur du Patrimoine, Musée des Beaux-Arts de Draguignan"
quote = "&ldquo;J’avais besoin de reprendre confiance en moi dans le cadre d’une négociation. Ses grandes qualités d’écoute et d’analyse m'ont aidé à mettre au point, au fil des séances de coaching, une stratégie pour gérer ma situation de manière optimale.&rdquo;"
[[params.testimonials.item]]
alt = "Stéphanie Baranger"
img = "person4.jpg"
person = "Stéphanie Baranger, Chief of staff to the Global Head of HR - Global Banking and Investor Solutions - Société Générale"
quote = "&ldquo;J’ai eu le plaisir de travailler avec Tristan sur un parcours de développement managérial (...) En faisant émerger une communauté de pratiques managériales consciente da sa valeur ajoutée, l’accompagnement de Tristan nous a permis d’aller bien au delà de l’objectif initial.&rdquo;"
[[params.testimonials.item]]
alt = "Verbatim1"
img = "person2.jpg"
person = "Verbatim évaluation à chaud"
quote = "&ldquo;Par la justesse de ses reformulations et feedbacks, Tristan a réussi à susciter chez les participants un changement de regard et l’envie d’oser. Tristan est un formateur qui sait créer un climat d'écoute, de bienveillance mais aussi de confrontation constructive.&rdquo;"
[[params.testimonials.item]]
alt = "Verbatim2"
img = "person1.jpg"
person = "Verbatim évaluation à chaud"
quote = "&ldquo;Tristan mobilise l'energie du groupe en jouant sur une grande variété de ressorts.&rdquo;"
[params.work]
enable = true
title = "Outils & certifications"
description = "Les outils que nous mobilisons font référence au niveau international et font l’objet d’une évaluation régulière. Process Communication©, Arc-en-Ciel DISC, Intelligence Emotionnelle, Psychologie Positive, Communication Non Violente, Codéveloppement."
    footertext = '<a href="" target="_blank"> </a>'

    [[params.work.row]]
      img = "AEC_1.png"
      alt = "DISC"
      title = "Arc-En-Ciel DISC"
      subtitle = "Connaître sa personnalité et ses motivations; mapping d'équipe"

    [[params.work.row]]
      img = "PCM-logo classic-2021-rgb.jpg"
      alt = "Process Communication Model"
      title = "Process Communication Model"
      subtitle = "Comprendre son comportement sous stress et mieux coopérer en équipe "

    [[params.work.row]]
      img = "Mentor.jpg"
      alt = "Codéveloppement"
      title = "Codéveloppement"
      subtitle = "Favoriser l'intelligence du groupe"
