# Site settings
baseurl = "https://www.tristandefommervault.com/"
title = "Tristan de Fommervault - Coach"
languageCode = "fr-fr"
theme = "elate"
footnoteReturnLinkContents = "↩"
metaDataFormat = "yaml"
removePathAccents = true

[params]
  # Custom styles
  custom_css = ["css/custom1.css"]

  # Meta
  author = "Tristan de Fommervault"
  description = "Coaching professionnel,mentoring,codéveloppement,process communication,approche systémique,analyse transactionnelle,communication non violente, intelligence émotionnelle, psychologie de la motivation, gestion du stress,prise de décision,régulation des conflits, médiation en entreprise, prévention des risques psychosociaux"
  email = "tdefommervault@qualia-management.com"
  # Navigation
  [params.navigation]
    brand = "Tristan de Fommervault - Coach"
    home = "Accueil"
    work = "Références"
    services = "Bio"
    testimonials = "Témoignages"
    contact = "Contact"
    about = "À propos"
    

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "/articles"
      name = "Articles"
      weight = 10
    [[menu.postpend]]
      url = "/formations"
      name = "Formations"
      weight = 20

  # Intro section
  [params.hero]
    title = ""
    subtitle = "Commençons par éclaircir votre besoin d'être accompagné"

  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Vous avez besoin de lever une difficulté qui freine votre avancée dans un projet"
    description = ""
    button = ""
    url = ""
    # button = "Why us?"
    icon = ""
    img = ""

          [[params.intro.item]]
            title = "Vous avez besoin de faire le point sur vos véritables forces et qualités pour retrouver confiance en vous et pouvoir jouer pleinement votre rôle"
            description = ""
            # url = "#"
            # button = "Click Me"
            icon = ""
            img = ""

            [[params.intro.item]]
              title = "Vous ressentez le besoin de reprendre en main votre GPS émotionnel"
              description = ""
              # url = "#"
              # button = "Click Me"
              icon = ""
              img = ""

              [[params.intro.item]]
                title = "Vous prenez conscience des limites de vos comportements sous stress et souhaitez développer des posture relationnelles constructives"
                description = ""
                # url = "#"
                # button = "Click Me"
                icon = ""
                img = ""


                  [[params.intro.item]]
                    title = "Vous avez besoin de résoudre un conflit et ressentez l'impression d'avoir déjà tout essayé"
                    description = ""
                    # url = "#"
                    # button = "Click Me"
                    icon = ""
                    img = ""

                    [[params.intro.item]]
                      title = " Vous avez 100 jours pour réussir votre prise de poste et avez besoin de vous recentrer sur vos priorités"
                      description = ""
                      # url = "#"
                      # button = "Click Me"
                      icon = ""
                      img = ""


                        # Hero section
                        [params.hero0]
                          title = "Mon approche du coaching"
                          subtitle = "La personne accompagnée retrouve progressivement, au travers des situations revisitées, ses sources d'énergie d’action. Elle développe une conscience de ses modes d'interaction et aiguise sa capacité à agir sur la base de stratégies efficaces."
  # Blog section


     [params.intro.video]
          enable = false
          title = "Voir la vidéo"
          icon = "icon-play2"
          url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = false
    title = "Work"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"
    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"
    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"



  # Services section
  [params.services]
    enable = true
    title = "Bio du coach"
    description = ""

    [[params.services.item]]
      title = "Tristan de Fommervault"
      description = "J'ai développé pendant 12 ans une approche de l'accompagnement des personnes engagées dans une histoire de transformation professionnelle et personnelle. Celle-ci offre un parcours pour mieux se connaître afin de devenir pleinement acteur de sa vie profesionnelle et personnelle. Elle permet de se rapprocher du Sens de son expérience vécue - en passant par les 5 sens - pour retrouver la source de son énergie d'action et s'épanouir dans la joie.   
      icon = ""


    [[params.services.item]]
      title = "Mes fondamentaux"
      description = "Trois cursus, trois clés de lecture : l'individu, le collectif, la relation. Une formation de 18 mois en coaching professionnel à l'Université de Paris 8 (Diplôme d'Etudes Supérieures de Coaching) et un parcours d'approfondissement en Philosophie, Histoire et Sociologie de l'entreprise (Diplôme d'Etudes Approfondies de l'Université Paris X / Master 2 Sciences Po Paris). Ma formation d'acteur au Conservatoire de Théâtre de Paris 7. "
      icon = ""

    [[params.services.item]]
      title = "Les modèles et outils que je mobilise"
      description = "J'intègre dans mes accompagnements : l'approche systémique, l'Analyse Transactionnelle, la Process Communication Model Coaching, les techniques du coaching cognitif et comportemental, les mises en situation"
      icon = ""

      [[params.services.item]]
      title = "Trois expériences marquantes"
      description = "Jouer sur scène, Explorer l'entreprise comme acteur intégré (Responsable RH) et intervenant extérieur en entreprise, Ecouter le nouveau"
      icon = ""

      [[params.services.item]]
      title = "Trois qualités"
      description = "Qualité d'écoute et de présence, enthousiasme, met en situation avec justesse pour rendre acteur"
      icon = ""

      # About section
    [params.about]
      enable = false
      title = "Qui sommes-nous ?"
      description = "Profils des intervenants"

      [[params.about.item]]
        name = "Tristan de Fommervault"
        position = "Coach et formateur certifié (Process Com., Desu Paris 8, Codeveloppement Mentor Trajectives). Sciences Po, M2 Philosophie et Humanités Sorbonne, Conservatoire de théâtre Paris. Tristan développe une approche de l'accompagnement des personnes et des collectifs en situation de transformation. Qualité d'écoute et de présence, enthousiasme communicatif, théâtralise avec justesse pour rendre acteur."
        img = "tristan.jpg"
        alt = "Tristan de Fommervault"
        social = [
          ["icon-twitter", "https://twitter.com/de_Fommervault"],
          ["icon-facebook", "https://www.facebook.com/fommervault?ref=bookmarks"],
          ["icon-linkedin", "https://www.linkedin.com/in/tristandefommervault/"]
        ]

      [[params.about.item]]
        name = "Léna Badach"
        position = "Partenaire experte en pédagogie, coach et formatrice certifiée Process Com."
        description = "Fondatrice du cabinet de coaching Acara. Auparavant Responsable des programmes internationaux de formation à l'ENA."
        img = "lena.jpg"
        alt = "lena"
        social = [
          ["icon-linkedin", "https://www.linkedin.com/in/tristandefommervault/"]
        ]

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Formations"
      icon = "icon-code"
      from = 0
      to = 2000
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Contact"
    description = ""

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "36 rue de Fleurus, <br> 75006 Paris"],
        ["icon-phone", "+33(0)6 61 07 90 51"],
        ["icon-envelope", "tdefommervault@qualia-management.com"],
        ["icon-globe", '<a href="https://tristandefommervault.com/" target="_blank">tristandefommervault.com</a>']
      ]

    name = "Nom"
    email = "Email"
    phone = "Téléphone"
    message = "Message"
    button = "Envoyer"

    # Testimonials section
    [params.testimonials]
      enable = true
      title = "Témoignages"
      description = ""

      [[params.testimonials.item]]
        quote = "&ldquo;Tristan a beaucoup apporté à ces ateliers grâce à sa personnalité engageante, son esprit d’ouverture et sa capacité à connecter des problématiques professionnelles avec une approche différente.&rdquo;"
        person = 'Sébastien Remond, <a href="https://cib.societegenerale.com/en/" target="_blank">Société Générale CIB</a> <span class="subtext">Directeur Investment Banking</span>'
        img = "person1.jpg"
        alt = "Sébastien Rémond"

      [[params.testimonials.item]]
        quote = "&ldquo;Tristan a fait preuve d'une grande intelligence des situations dans un contexte de transformation majeure de l'entreprise.&rdquo;"
        person = 'Catherine Belotti, <span class="subtext">Directrice innovation sociale Schneider Electric</span>'
        img = "person2.jpg"
        alt = "Catherine Belotti"

      [[params.testimonials.item]]
        quote = "&ldquo;J’avais besoin de reprendre confiance en moi dans le cadre d’une négociation. Ses grandes qualités d’écoute et d’analyse m'ont aidé à mettre au point, au fil des séances de coaching, une stratégie pour gérer ma situation de manière optimale.&rdquo;"
        person = 'Grégoire Hallé, Conservateur du Patrimoine, Musée des Beaux-Arts de Draguignan'
        img = "person3.jpg"
        alt = "Grégoire hallé"

      [[params.testimonials.item]]
      quote = "&ldquo;J’ai eu le plaisir de travailler avec Tristan sur un parcours de développement managérial (...) En faisant émerger une communauté de pratiques managériales consciente da sa valeur ajoutée, l’accompagnement de Tristan nous a permis d’aller bien au delà de l’objectif initial.&rdquo;"
      person = 'Stéphanie Baranger, Chief of staff to the Global Head of HR - Global Banking and Investor Solutions - Société Générale'
      img = "person4.jpg"
      alt = "Stéphanie Baranger"

      [[params.testimonials.item]]
      quote = "&ldquo;Par la justesse de ses reformulations et feedbacks, Tristan a réussi à susciter chez les participants un changement de regard et l’envie d’oser. Tristan est un formateur qui sait créer un climat d'écoute, de bienveillance mais aussi de confrontation constructive.&rdquo;"
      person = 'Verbatim évaluation à chaud'
      img = "person2.jpg"
      alt = "Verbatim1"

      [[params.testimonials.item]]
      quote = "&ldquo;Tristan mobilise l'energie du groupe en jouant sur une grande variété de ressorts.&rdquo;"
      person = 'Verbatim évaluation à chaud'
      img = "person1.jpg"
      alt = "Verbatim2"

      # Blog section
  [params.articles]
  enable = true
  title = "Articles"
  description = "Food for thought"


  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Tristan de Fommervault. Tous droits réservés.'
    links = [
        ["icon-facebook", "https://www.facebook.com/tristandefommervault"],
        ["icon-linkedin", "https://fr.linkedin.com/in/tristandefommervault/fr"]
      ]
