baseurl = "https://www.tristandefommervault.com/"
footnoteReturnLinkContents = "↩"
languageCode = "fr-fr"
metaDataFormat = "yaml"
removePathAccents = true
theme = "elate"
title = "Tristan de Fommervault - coach & formateur"
[[menu.postpend]]
name = "Bio"
url = "/bio"
weight = 3
[[menu.postpend]]
name = "Articles"
url = "/articles"
weight = 1
[[menu.postpend]]
name = "Formations"
url = "/formations"
weight = 2
[params]
author = "Tristan de Fommervault"
custom_css = ["css/custom1.css"]
description = "Coaching, Management, Co-développement"
email = "tdefommervault@qualia-management.com"
[params.about]
description = "Profils des intervenants"
enable = true
title = "Qui sommes-nous ?"
[[params.about.item]]
alt = "Tristan de Fommervault"
description = "Un regard expérimenté sur les phénomènes de transformation, croisant avec pertinence les expertises et les pratiques, pour fabriquer des lieux vivants catalyseurs de leadership."
img = "tristan.jpg"
name = "Tristan de Fommervault"
position = "Consultant-formateur et coach, fondateur de Qualia Management®"
social = [["icon-twitter", "https://twitter.com/de_Fommervault"], ["icon-facebook", "https://www.facebook.com/fommervault?ref=bookmarks"], ["icon-linkedin", "https://www.linkedin.com/in/tristandefommervault/"]]
[[params.about.item]]
alt = "lena"
description = "Fondatrice du cabinet de coaching Acara. Auparavant Responsable des programmes internationaux de formation à l'ENA. Ancre sa pratique dans les différents courants de la tradition chinoise."
img = "lena.jpg"
name = "Léna Badach"
position = "Partenaire experte en pédagogie, bien-être et communication"
social = [["icon-linkedin", "https://www.linkedin.com/in/tristandefommervault/"]]
[params.articles]
description = "Apprendre à manager vos équipes"
enable = true
title = "Articles"
[params.contact]
button = "Envoyer"
description = "Nous sommes à votre écoute."
details = [["icon-home", "36 rue de Fleurus, <br> 75006 Paris"], ["icon-phone", "+33(0)6 61 07 90 51"], ["icon-envelope", "tdefommervault@qualia-management.com"], ["icon-globe", "<a href=\"https://tristandefommervault.com/\" target=\"_blank\">tristandefommervault.com</a>"]]
email = "Email"
enable = true
form = true
map = false
message = "Message"
name = "Nom"
phone = "Téléphone"
title = "Contact"
[params.counters]
background = "full_image_1.jpg"
enable = false
title = "Stats"
[[params.counters.item]]
description = "Finished projects"
from = 0
icon = "icon-briefcase"
interval = 50
speed = 5000
to = 89
[[params.counters.item]]
description = "Formations"
from = 0
icon = "icon-code"
interval = 50
speed = 5000
to = 2000
[[params.counters.item]]
description = "Cups of coffee"
from = 0
icon = "icon-cup"
interval = 50
speed = 5000
to = 1302
[[params.counters.item]]
description = "Happy clients"
from = 0
icon = "icon-people"
interval = 50
speed = 5000
to = 52
[params.footer]
copyright = "&copy; Tristan de Fommervault. Tous droits réservés."
enable = true
links = [["icon-github", "https://github.com/qualia"], ["icon-linkedin", "https://fr.linkedin.com/in/tristandefommervault/fr"]]
[params.hero]
subtitle = "Un accompagnement sur mesure pour vos équipes."
title = "Coaching et formation"
[params.intro.video]
enable = false
icon = "icon-play2"
title = "Voir la vidéo"
url = "https://vimeo.com/channels/staffpicks/93951774"
[[params.intro.item]]
description = "Prendre sa place"
icon = "icon-rocket"
img = "img_10.jpg"
title = "Coaching individuel"
[[params.intro.item]]
description = "Améliorez la cohésion de l'équipe"
icon = "icon-group"
img = "img_10.jpg"
title = "Coaching d'équipe"
[[params.intro.item]]
description = "Un problème vous résiste, trouvons une solution ensemble."
icon = "icon-group"
img = "img_8.jpg"
title = "Co-développement"
[[params.intro.item]]
description = "Inscrivez-vous sur notre calendriers des formations."
icon = "icon-calendar"
img = "img_7.jpg"
title = "Prochaines sessions"
[params.navigation]
about = "À propos"
brand = "Tristan de Fommervault"
contact = "Contact"
home = "Accueil"
services = "Services"
testimonials = "Témoignages"
work = "Références"
[params.services]
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
enable = false
title = "Services"
[[params.services.item]]
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
icon = "icon-anchor"
title = "Brand &amp; Strategy"
[[params.services.item]]
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
icon = "icon-layers2"
title = "Web &amp; Interface"
[[params.services.item]]
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
icon = "icon-video2"
title = "Photo &amp; Video"
[[params.services.item]]
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
icon = "icon-monitor"
title = "CMS &amp; eCommerce"
[params.testimonials]
description = "Nos clients parlent de leur expérience de l'accompagnement."
enable = true
title = "Témoignages"
[[params.testimonials.item]]
alt = "Sébastien Rémond"
img = "person1.jpg"
person = "Sébastien Remond, <a href=\"https://cib.societegenerale.com/en/\" target=\"_blank\">Société Générale CIB</a> <span class=\"subtext\">Directeur Investment Banking</span>"
quote = "&ldquo;Tristan a beaucoup apporté à ces ateliers grâce à sa personnalité engageante, son esprit d’ouverture et sa capacité à connecter des problématiques professionnelles avec une approche différente.&rdquo;"
[[params.testimonials.item]]
alt = "Catherine Belotti"
img = "person2.jpg"
person = "Catherine Belotti, <span class=\"subtext\">Directrice innovation sociale Schneider Electric</span>"
quote = "&ldquo;Tristan a fait preuve d'une grande intelligence des situations dans un contexte de transformation majeure de l'entreprise.&rdquo;"
[[params.testimonials.item]]
alt = "Grégoire hallé"
img = "person3.jpg"
person = "Grégoire Hallé, Conservateur du Patrimoine, Musée des Beaux-Arts de Draguignan"
quote = "&ldquo;J’avais besoin de reprendre confiance en moi dans le cadre d’une négociation. Ses grandes qualités d’écoute et d’analyse m'ont aidé à mettre au point, au fil des séances de coaching, une stratégie pour gérer ma situation de manière optimale.&rdquo;"
[[params.testimonials.item]]
alt = "Stéphanie Baranger"
img = "person4.jpg"
person = "Stéphanie Baranger, Chief of staff to the Global Head of HR - Global Banking and Investor Solutions - Société Générale"
quote = "&ldquo;J’ai eu le plaisir de travailler avec Tristan sur un parcours de développement managérial 'agile' (...) En faisant émerger une communauté de pratiques managériales consciente da sa valeur ajoutée, l’accompagnement de Tristan nous a permis d’aller bien au delà de l’objectif initial.&rdquo;"
[[params.testimonials.item]]
alt = "Verbatim1"
img = "person2.jpg"
person = "Verbatim évaluation à chaud"
quote = "&ldquo;Par la justesse de ses reformulations et feedbacks, Tristan a réussi à susciter chez les participants un changement de regard et l’envie d’oser. Tristan est un formateur qui sait créer un climat d'écoute, de bienveillance mais aussi de confrontation constructive.&rdquo;"
[[params.testimonials.item]]
alt = "Verbatim2"
img = "person1.jpg"
person = "Verbatim évaluation à chaud"
quote = "&ldquo;Tristan mobilise l'energie du groupe en jouant sur une grande variété de ressorts.&rdquo;"
[params.work]
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
enable = false
footertext = "** Demo images from <a href=\"http://plmd.me/\" target=\"_blank\">plmd.me</a>"
title = "Work"
[[params.work.row]]
alt = "Image2"
img = "work_1.jpg"
subtitle = "Branding"
title = "Project 1"
[[params.work.row]]
alt = "Image2"
img = "work_2.jpg"
subtitle = "Design"
title = "Project 2"
[[params.work.row]]
alt = "Image3"
img = "work_3.jpg"
subtitle = "Design"
title = "Project 3"
[[params.work.row]]
alt = "Image4"
img = "work_4.jpg"
subtitle = "Design"
title = "Project 4"
[[params.work.row]]
alt = "Image5"
img = "work_5.jpg"
subtitle = "Design"
title = "Project 5"
[[params.work.row]]
alt = "Image6"
img = "work_6.jpg"
subtitle = "Design"
title = "Project 6"
