---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/formations
  label: Formations
  create: all
  match: "**/*.md"
  exclude: "**/*index.md"
  templates:
  - formation
- type: directory
  path: content/articles
  label: Articles
  create: all
  match: "**/*"
  exclude: "**/*index.md"
  templates:
  - article
- type: heading
  label: Pages
- type: document
  path: content/formations/_index.md
  label: Formations
- type: document
  path: content/coaching/index.md
  label: Coaching
upload_dir: tdf
public_path: https://res.cloudinary.com/qualia-management/image/upload/ar_1.6,c_crop,w_649,g_auto,f_auto,q_auto
front_matter_path: https://res.cloudinary.com/qualia-management/image/upload
use_front_matter_path: true
file_template: ":filename: "
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.53'
